on: [workflow_dispatch]
jobs:
  test:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: windows-latest
            name: Windows 32
            args: "--cpu=i386"
            fpclazup-url: https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/releases/download/v2.4.0g/fpclazup-x86_64-win64.exe
            fpclazup-lazcommit: 98f9c7a7a102139e43b39050ebbb5c48d805f59f # 4.4
            fpclazup-fpccommit: de30ac10d4f228c5d4915c49d48715063ea55787 # trunk (~3.3)

          - os: ubuntu-24.04-arm
            name: Linux ARM64
            args: ""
            fpclazup-url: https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/releases/download/v2.4.0g/fpclazup-aarch64-linux
            fpclazup-lazcommit: 98f9c7a7a102139e43b39050ebbb5c48d805f59f # 4.4
            fpclazup-fpccommit: de30ac10d4f228c5d4915c49d48715063ea55787 # trunk (~3.3)

          - os: macos-latest
            name: MacOS arm64
            args: ""
            fpclazup-url: https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/releases/download/v2.4.0g/fpclazup-aarch64-darwin
            fpclazup-lazcommit: 98f9c7a7a102139e43b39050ebbb5c48d805f59f # 4.4
            fpclazup-fpccommit: de30ac10d4f228c5d4915c49d48715063ea55787 # trunk (~3.3)
        
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        
      - name: Install Lazarus
        uses: ollydev/setup-lazarus@v4
        with:
          fpclazup-url: ${{ matrix.config.fpclazup-url }}
          fpclazup-lazcommit: ${{ matrix.config.fpclazup-lazcommit }}
          fpclazup-fpccommit: ${{ matrix.config.fpclazup-fpccommit }}
      
      - name: Test Installation
        run: |
          lazbuild --version

      - name: Build demos with FPC (Linux)
        if: runner.os == 'Linux'
        shell: bash
        run:  |
          cd Scripts
          ./BuildDemosFPC.sh
          ./BuildExtDemosFPC.sh
          ./Clean.sh --clean-also-bin-dirs
     
      - name: Build demos with FPC (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run:  |
          cd Scripts
          ./BuildDemosFPC.bat
          ./BuildExtDemosFPC.bat
          ./Clean.sh --clean-also-bin-dirs
     
      - name: Build demos with Lazarus
        shell: bash
        run:  |
          cd Demos/ObjectPascal
          # Built for all platforms
          lazbuild --bm="Release" "Benchmark/Bench.lpi"
          lazbuild --bm="Release" "VampConvert/VampConvert.lpi"
          if [ "$RUNNER_OS" == "Linux" ]; then
              # For Linux build LCL demos also with Qt5 (just to test that it builds)
              lazbuild --ws=qt5 --bm="Release" "LCLImager/lclimager.lpi"
              lazbuild --ws=qt5 --bm="Release" "ImageBrowser/ImgBrowser.lpi"
              lazbuild --ws=gtk2 --opt="-oLCLImager-GTK2" --bm="Release" "LCLImager/lclimager.lpi"
              lazbuild --ws=gtk2 --opt="-oLCLImager-GTK2-Debug" --bm="Debug" "LCLImager/lclimager.lpi"
          fi
          if [ "$RUNNER_OS" != "macOS" ]; then
              # Build these for non macOS platforms
              lazbuild --bm="Release" "LCLImager/lclimager.lpi"
              lazbuild --bm="Release" "ImageBrowser/ImgBrowser.lpi"
              lazbuild --bm="Release" "OpenGLDemo/OpenGLDemo.lpi"
              lazbuild --bm="Release" "SDLDemo/SDLDemo.lpi"
          fi
          if [ "$RUNNER_OS" == "Windows" ]; then
              # Build D3D demo just for Windows
              lazbuild --bm="Release" "D3DDemo/D3DDemo.lpi"
          fi
          if [ "$RUNNER_OS" == "macOS" ]; then
              # For macOS we need to build LCL demos with Cocoa
              lazbuild --ws=cocoa --bm="Release" "LCLImager/lclimager.lpi"
              lazbuild --ws=cocoa --bm="Release" "ImageBrowser/ImgBrowser.lpi"
          fi
  
      - name: List Demos Bin directory
        shell: bash
        run:  ls Demos/Bin
    
      - name:  Run demos
        shell: bash
        run:   |
          cd Demos/Bin
          ./Bench
          ./VampConvert -h
     
      - name: Compile Lazarus Packages
        shell: bash
        run:  |
          lazbuild "Packages/VampyreImagingPackage.lpk"
          lazbuild "Packages/VampyreImagingPackageExt.lpk"    
