on: [workflow_dispatch]
jobs:
  test:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: windows-latest
            name: Windows 32
            args: "--cpu=i386"
            fpclazup-url: https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/releases/download/v2.4.0g/fpclazup-x86_64-win64.exe
            fpclazup-lazcommit: 98f9c7a7a102139e43b39050ebbb5c48d805f59f # 4.4
            fpclazup-fpccommit: de30ac10d4f228c5d4915c49d48715063ea55787 # trunk (~3.3)

          - os: ubuntu-24.04-arm
            name: Linux ARM64
            args: ""
            fpclazup-url: https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/releases/download/v2.4.0g/fpclazup-aarch64-linux
            fpclazup-lazcommit: 98f9c7a7a102139e43b39050ebbb5c48d805f59f # 4.4
            fpclazup-fpccommit: de30ac10d4f228c5d4915c49d48715063ea55787 # trunk (~3.3)

          - os: macos-latest
            name: MacOS arm64
            args: ""
            fpclazup-url: https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/releases/download/v2.4.0g/fpclazup-aarch64-darwin
            fpclazup-lazcommit: 98f9c7a7a102139e43b39050ebbb5c48d805f59f # 4.4
            fpclazup-fpccommit: de30ac10d4f228c5d4915c49d48715063ea55787 # trunk (~3.3)
        
    steps:
      - name: Install Lazarus
        uses: ollydev/setup-lazarus@v4
        with:
          fpclazup-url: ${{ matrix.config.fpclazup-url }}
          fpclazup-lazcommit: ${{ matrix.config.fpclazup-lazcommit }}
          fpclazup-fpccommit: ${{ matrix.config.fpclazup-fpccommit }}
      
      - name: Test Installation
        run: |
          lazbuild --version
